import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "./navbar";
import Footer from "./footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Start Minecraft",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="w-full min-h-[100svh] h-fit flex md:flex-row md:items-start items-center justify-start md:justify-center flex-col bg-gradient-to-b from-[#101F2C] to-[#132535]">
          <Navbar />

          <div className="md:w-[70%] w-full h-full">
            {children} <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
